import Head from 'next/head'

import { useSession, signIn, signOut } from "next-auth/react"

export default function Home() {

  const {data: session} = useSession()
  return (
    <div>
      <Head>
        <title>Basic Next-Auth App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!session && (
          <button onClick={() => signIn()}>Sign in with GitHub</button>
        )}
        {session && (
          <button onClick={() => signOut()}>Sign Out ({session.user.name})</button>
        )}

        <h1>This is the page here.</h1>
      </main>
    </div>
  )
}
